### ISSUE TITLE
GCS

### ISSUE THREAD

**Issue by Yaandle** [Yaandle/ImageFinder#31]
Google Cloud Storage Integration
Google Cloud Storage account.
Service account key for authentication.
Configuration:
Configure GCS credentials with your service account key.
Develop Python functions for image database interaction (list, upload, download, delete).
Implement logic to retrieve images based on 'Bike Number'.
Download relevant images for processing.
Apply object detection and filtering logic.
Manage image storage (retain or delete) for cost and cleanliness.

**Comment by Yaandle** [comment]
Google Cloud Services are used for the project database. New images are uploaded for detections. The relevant code will be in the python app. When're the 'bike number' is processed.

**Comment by Yaandle** [comment]
I setup a database but cannot retrieve any images from the database

**Comment by Yaandle** [comment]
E:\Machine Learning\Object Detection>python google.py
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.15.2\src\err\mod.rs:582:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "E:\Machine Learning\Object Detection\google.py", line 2, in <module>
    from google.cloud import storage
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\cloud\storage\__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\cloud\storage\batch.py", line 42, in <module>
    from google.cloud import _helpers
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\cloud\_helpers\__init__.py", line 31, in <module>
    import google.auth.transport.requests
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\auth\transport\requests.py", line 48, in <module>
    from google.oauth2 import service_account
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\oauth2\service_account.py", line 77, in <module>
    from google.auth import _service_account_info
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\auth\_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\auth\crypt\__init__.py", line 43, in <module>
    from google.auth.crypt import rsa
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\auth\crypt\rsa.py", line 20, in <module>
    from google.auth.crypt import _cryptography_rsa
  File "C:\Users\Bozzy\AppData\Roaming\Python\Python310\site-packages\google\auth\crypt\_cryptography_rsa.py", line 25, in <module>
    from cryptography.hazmat.primitives import serialization
  File "D:\Python\lib\site-packages\cryptography\hazmat\primitives\serialization\__init__.py", line 16, in <module>
    from cryptography.hazmat.primitives.serialization.base import (
  File "D:\Python\lib\site-packages\cryptography\hazmat\primitives\serialization\base.py", line 9, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import (
  File "D:\Python\lib\site-packages\cryptography\hazmat\primitives\asymmetric\types.py", line 8, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File "D:\Python\lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 10, in <module>
    from cryptography.hazmat.primitives.asymmetric import utils as asym_utils
  File "D:\Python\lib\site-packages\cryptography\hazmat\primitives\asymmetric\utils.py", line 6, in <module>
    from cryptography.hazmat.bindings._rust import asn1
pyo3_runtime.PanicException: Python API call failed

**Comment by Yaandle** [comment]
Display an image from GCS bucket.

**Comment by Yaandle** [comment]
Save filtered images to a different bucket.

**Comment by Yaandle** [comment]
Store and manage data using a MySQL database with Cloud SQL.
